指摘箇所を修正。
Tshi66/PFpractice pull request #12
Opened 2020-01-27 14:27 UTC by Tshi66

各指摘箇所に対して、修正を行いました✍️

再度レビューをお願いいたします！

2020-01-28 02:48 UTC, yamataku29 submitted a review, later dismissed
いくつかコメントしました🙆‍♂️

2020-01-28 02:48 UTC, yamataku29 commented on PFpractice/Controller/CreatePostViewController.swift
> +    internal func textFieldShouldReturn(_ textField: UITextField) -> Bool {
functionはデフォルトで`internal`なので、この表記はなくてもよさそうですね🙆‍♂️

2020-01-28 02:48 UTC, yamataku29 commented on PFpractice/Controller/CreatePostViewController.swift
> +    private func setImgPicker(){
指摘していない内容で恐縮ですが、private functionが複数ある場合はextensionとして切り出すのが良いかも知れません💡
```swift

private extension CreatePostViewController {
  func setImgPicker() {
    // private functionになる
  }
}
```

2020-01-28 02:48 UTC, yamataku29 commented on PFpractice/Controller/CreatePostViewController.swift
> +        let color = AppTheme().mainColor
あれ？`AppTheme`というクラスを作っていないようですが、これだとコンパイルエラーになりませんか？🤔

2020-01-28 02:48 UTC, yamataku29 commented on PFpractice/Controller/EditPostViewController.swift
> +        post.date = self.dateTextField.text ?? "2020/01/01"
ここはデフォルト文字列を`2020/01/01`にしちゃうと不具合とか出ないですか？👀

2020-01-28 09:36 UTC, Tshi66 commented on PFpractice/Controller/CreatePostViewController.swift
> +        let color = AppTheme().mainColor
作成したAppThemeのファイルをコミットし忘れました！！
失礼いたしました😰

2020-01-28 10:18 UTC, Tshi66 commented on PFpractice/Controller/CreatePostViewController.swift
> +    private func setImgPicker(){
複数あるprivate functionを全て、extensionとして切り出すということでしょうか？🤔

2020-01-28 14:32 UTC, yamataku29 commented on PFpractice/Controller/CreatePostViewController.swift
> +    private func setImgPicker(){
はい！その認識です👌

2020-01-28 15:13 UTC, Tshi66 commented
110a599

コード修正しました！🚀
レビューをお願いいたします！🙏

### ご指摘箇所＆修正箇所
- internal表記の削除
- extensionとして切り出す
- AppThemeのファイルをコミット
- デフォルト文字列を`2020/01/01`を`""`に変更

2020-01-28 15:27 UTC, yamataku29 requested changes
いくつかコメントしました〜🙆‍♂️

2020-01-28 15:27 UTC, yamataku29 commented on PFpractice/Controller/BankViewController.swift
> +    private func showEditSavingAlert() {
あ、ここはちょっと意図が異なりますね😅
private extension内は全て「private扱いになる」ので、当該ブロックのスコープにおいてprivate修飾子を付けたらその内部は普通にfunctionにするだけよいです👌

```swift
extension ClassName {
    func test() {
        // これは普通にinternal function
    }
}

private extension ClassName {
    func test() {
        // これはprivate functionになるので、`private`をわざわざ付与する必要が無い
    }
}
```

2020-01-28 15:27 UTC, yamataku29 commented on PFpractice/Controller/BankViewController.swift
> +            if amount < 0 {
これも三項演算子にできそうですね👏

2020-01-28 15:27 UTC, yamataku29 commented on PFpractice/Controller/BankViewController.swift
> +        if pattern == 0 {
このパターンはInt型ではなく、独自のenumクラスを作成するとよいでしょう💁‍♂️
https://qiita.com/hachinobu/items/392c96820588d1c03b0c
パターン0と1がそれぞれどんな意味を持つのかによってenumの名前を決めて上げるよよいですね。

2020-01-28 15:27 UTC, yamataku29 commented on PFpractice/Controller/BankViewController.swift
> +        } else {
因みに上述したenumにしてあげることでif文ではなくSwitch文に書き換えられるはずです💡
そうすると、意図しない例外ケースが発生することがない(if文だとelseスコープにおいてさまざまな例外が発生してしまう)ため、通常はif文よりもenumを活用したSwitch文の方がよりバグの少ない安全な書き方と言えます🙆‍♂️

2020-01-28 15:27 UTC, yamataku29 commented on PFpractice/Controller/CreatePostViewController.swift
> +        post.budget = Int(self.budgetTextField.text ?? "") ?? 0
因みにここって空文字("")が入ってもシステム的に問題ないんですかね👀
問題ないのであればよいのですが、そもそもここに空文字が入る想定ではないのであれば、空文字が来た際にはアラートを表示するなどのエラーハンドリングをしなければいけませんが、そのあたりは考慮できていますか？

2020-01-28 15:27 UTC, yamataku29 commented on PFpractice/Struct/AppTheme.swift
> +    let mainColor = UIColor(red: 219/255, green: 68/255, blue: 55/255, alpha: 1.0)
ここはstatic propertyにしてあげることで、わざわざ`AppTheme`をインスタンス化しなくて済むので、そちらの方がベターですね🙆‍♂️
https://qiita.com/shtnkgm/items/b1cdedc1c7d4bfe6e9fe

2020-01-29 07:03 UTC, Tshi66 commented on PFpractice/Controller/BankViewController.swift
> +            if amount < 0 {
三項演算子に、うまく変換できません。

どのように三項演算子を使ったコードに変換できるのか、
アドバイスを頂戴したいです。🙏

以下修正したコード
```swift

(text: progressLabel.text, color: progressLabel.textColor) = {
            
            let amount = sumBudget - bank.saving
            
            amount < 0 ? (text: "余り \(-(amount))円", color: .blue) : (text: "あと \(amount)円", color: .red)

           //以下のコードでも同じエラーが出ます。
            amount < 0 ? return(text: "余り \(-(amount))円", color: .blue) : return(text: "あと \(amount)円", color: .red)
            
//            修正前
//            if amount < 0 {
//                return (text: "余り \(-(amount))円", color: .blue)
//
//            } else {
//                return (text: "あと \(amount)円", color: .red)
//            }

 }()

```

発生したエラー: `Expression type '(text: _, color: _)' is ambiguous without more context`

(text: _, color: _)の形式では、エラーが出るみたいです。

参考にしたサンプルコード
```swift
let isSelected = true

if isSelected {
    print("true")
} else {
    print("false")
}
// ↓同じ
isSelected ? print("true") : print("false")
```

2020-01-29 07:24 UTC, yamataku29 commented on PFpractice/Controller/BankViewController.swift
> +            if amount < 0 {
こんな感じだとどうでしょう？💁‍♂️
```swift
let amount = sumBudget - bank.saving
return amount < 0 ? (text: "余り \(-(amount))円", color: .blue) : 
                (text: "あと \(amount)円", color: .red)
```

2020-01-29 08:24 UTC, Tshi66 commented on PFpractice/Controller/BankViewController.swift
> +            if amount < 0 {
上手く動作しました！！
ありがとうございます！✨

2020-01-29 08:50 UTC, Tshi66 commented on PFpractice/Controller/CreatePostViewController.swift
> +        post.budget = Int(self.budgetTextField.text ?? "") ?? 0
以下のメソッドで、テキストフィールドに入力された文字列に対してバリデーション をかけています。
```swift

func validateTextField() {
        
        //空白文字が含むとエラー
        let stringRule = ValidationRulePattern(pattern: "^[\\S]+$", error: ExampleValidationError("空白等は含めないで下さい"))
        //数字以外はエラー
        let budgetRule = ValidationRulePattern(pattern: "^[\\d]+$", error: ExampleValidationError("金額を入力して下さい"))
        //20../../..の型でないとエラー
        let dateRule = ValidationRulePattern(pattern: "20../../..", error: ExampleValidationError("日付を入力して下さい"))
        
        applyRuleToTF(textField: nameTextField, rule: stringRule, VDLabel: nameVdLabel)
        applyRuleToTF(textField: themeTextField, rule: stringRule, VDLabel: themeVdLabel)
        applyRuleToTF(textField: presentTextField, rule: stringRule, VDLabel: presentVdLabel)
        applyRuleToTF(textField: dateTextField, rule: dateRule, VDLabel: dateVdLabel)
        applyRuleToTF(textField: budgetTextField, rule: budgetRule, VDLabel: budgetVdLabel)
        
    }
    
func applyRuleToTF(textField: UITextField, rule: ValidationRulePattern, VDLabel: UILabel) {
        
        let validateTF = textField.validate(rule: rule)
        reflectValidateResalut(result: validateTF, label: VDLabel)
 }
    
func reflectValidateResalut(result: ValidationResult, label: UILabel) {
        switch result {
        case .valid:
            label.text = "ok"
        case .invalid(let failures):
            label.text = (failures.first as? ExampleValidationError)?.message
        }
 }
```
`inputContentToPost()`メソッドが作動する前に、バリデーションを通過しますので、
そもそも空文字が入ることは有り得ません。
```
func inputContentToPost() {
        
        post.name = self.nameTextField.text ?? ""
        post.theme = self.themeTextField.text ?? ""
        post.present = self.presentTextField.text ?? ""
        post.date = self.dateTextField.text ?? ""
        post.budget = Int(self.budgetTextField.text ?? "") ?? 0
        post.backImage = self.backImageView.image
        post.photo = self.heroImageView.image
   
 }
```

ですので、`post.name = self.nameTextField.text !`のように、強制アンラップをしても問題ない設定にしていたつもりでした。🤔

その上で、実現したいことは以下になりますので
アドバイスをいただければと思います！🙏

- 強制アンラップを避ける
- `?? ""`のようなデフォルト値の設定もしない（する必要がないはずなので）

テキストフィールドに対するバリデーションのアプリ画面の挙動↓
<img width="357" alt="スクリーンショット 2020-01-29 17 48 03" src="https://user-images.githubusercontent.com/47974150/73341195-81ace580-42bf-11ea-8861-6f1f819a13f2.png">

2020-01-30 11:22 UTC, yamataku29 commented on PFpractice/Controller/CreatePostViewController.swift
> +        post.budget = Int(self.budgetTextField.text ?? "") ?? 0
背景について、理解しました！
> inputContentToPost()メソッドが作動する前に、バリデーションを通過しますので、
そもそも空文字が入ることは有り得ません。

上記の前提であれば、むしろここでプログラムを止める(=アプリを落とす)運用が正しいと思います🙆‍♂️
なぜなら、ここが空文字だった場合はそもそもアプリ運用上望ましくないのでデータを保存させないためにオペレーションを終了させないといけないからですね。

2020-01-30 11:23 UTC, yamataku29 commented on PFpractice/Controller/CreatePostViewController.swift
> +        post.budget = Int(self.budgetTextField.text ?? "") ?? 0
僕ならUITextField.textのオプショナルバインディングをする際にバリデーションをしますが、現状の実装でも全然問題は無いと思います👌

2020-01-30 15:43 UTC, Tshi66 commented
ご指摘箇所、修正いたしました。
レビューの方、どうぞよろしくお願いいたします！🙏

2020-01-31 00:36 UTC, yamataku29 reviewed
1点だけコメントしました〜🙆‍♂️

2020-01-31 00:36 UTC, yamataku29 commented on PFpractice/Controller/EditPostViewController.swift
> +    private func iconSetToLabel(){
このあたりのprivate extensionで切り出せそうですが、何かそうしない理由などがありそうでしょうか？👀

2020-01-31 04:23 UTC, Tshi66 commented on PFpractice/Controller/EditPostViewController.swift
> +    private func iconSetToLabel(){
>private extensionで切り出せそうですが、何かそうしない理由などがありそうでしょうか？

理由ありません。。
修正忘れでした。😰
お手数かけました！🙇‍♂️

e9eaafd
→コード修正いたしました！
再度のレビューをお願いいたします。🙏

2020-01-31 07:48 UTC, yamataku29 commented on PFpractice/Controller/EditPostViewController.swift
> +    private func iconSetToLabel(){
オケです！👌
コードレビューを送る前に「セルフレビュー」と言って、自分の実装の差分を見て自分でレビューをする習慣をつけるとよいですよ🙆‍♂️

2020-01-31 07:48 UTC, yamataku29 approved these changes
素晴らしい!!!
LGTM😆🎉

2020-01-31 08:48 UTC, merged